// Generated by CoffeeScript 1.3.3
(function() {

  module.exports.setup = function(app) {
    app.get('/contact', function(req, res) {
      return res.render('contact', {
        successful_send: req.flash('sucess')
      });
    });
    app.post('/contact', function(req, res) {
      var mandrill;
      mandrill = require('node-mandrill')('3a76a23d-168a-4a5e-ad36-c9df471fa3a0');
      mandrill('/messages/send', {
        message: {
          to: [
            {
              email: 'matt.sencenbaugh@gmail.com',
              name: 'Matt Sencenbaugh'
            }
          ],
          from_email: req.body.email,
          subject: "New mail from Sencedev.com",
          text: req.body.message
        }
      }, function(error, response) {
        console.log(JSON.stringify(error));
        return console.log(response);
      });
      req.flash('sucess', 'Thanks for your email, I will be in touch shortly!');
      return res.redirect('/contact');
    });
  };

}).call(this);
