// Generated by CoffeeScript 1.3.3
(function() {
  var NavigationLink;

  NavigationLink = (function() {

    function NavigationLink(title, url) {
      this.title = title;
      this.url = url;
    }

    return NavigationLink;

  })();

  NavigationLink.portfolio_links = function() {
    [new NavigationLink(" About", "/"), new NavigationLink(" Projects", "/projects"), new NavigationLink(" Skills", "/skills"), new NavigationLink(" Contact", "/contact")];
    return module.exports = NavigationLink;
  };

}).call(this);
