// Generated by CoffeeScript 1.3.3
(function() {
  var Skill;

  Skill = (function() {

    function Skill(name, years, width) {
      this.name = name;
      this.years = years;
      this.width = width;
    }

    return Skill;

  })();

  Skill.portfolio_skills = function() {
    return [new Skill("iOS", "4 years", 100), new Skill("HTML/CSS", "4 years", 100), new Skill("Javascript", "3 years", 75), new Skill("Ruby on Rails", "2 years", 50), new Skill("Java", "2 years", 50), new Skill("Python", "1 year", 25), new Skill("C", "1 year", 25), new Skill("Photoshop", "1 year", 25)];
  };

  module.exports.setup = function(app) {
    var skills;
    skills = Skill.portfolio_skills();
    return app.get('/skills', function(req, res) {
      return res.render('skills', {
        skills: skills
      });
    });
  };

  module.exports = Skill;

}).call(this);
