// Generated by CoffeeScript 1.3.3
(function() {
  var AppForms, NavigationLink, Project, Skill, app, express, flash, pub;

  flash = require('connect-flash');

  express = require('express');

  app = express();

  pub = __dirname + '/public';

  app.use(express["static"](pub));

  app.use(express.errorHandler());

  app.use(express.bodyParser());

  app.use(express.cookieParser('SencedevPortfolioSecret'));

  app.use(express.session());

  app.use(flash());

  NavigationLink = require('./models/navigation_link.js');

  app.use(function(req, res, next) {
    res.locals.navigationLinks = NavigationLink.portfolio_links();
    res.locals.path = req.path;
    return next();
  });

  app.use(app.router);

  app.set('views', __dirname + '/views');

  app.set('view engine', 'jade');

  Skill = require('./models/skill.js');

  Skill.setup(app);

  Project = require('./models/project.js');

  Project.setup(app);

  AppForms = require('./models/form.js');

  AppForms.setup(app);

  app.get('/', function(req, res) {
    return res.render('about');
  });

  app.listen(3000);

  console.log('listening on port 3000');

}).call(this);
